export const TOKEN_GET_START = 'TOKEN_GET_START'
export const TOKEN_GET_SUCCESS = 'TOKEN_GET_SUCCESS'
export const TOKEN_GET_FAIL = 'TOKEN_GET_FAIL'

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const PRODUCTS_GET_NEW_LIST_START = 'PRODUCTS_GET_NEW_LIST_START'
export const PRODUCTS_GET_NEW_LIST_SUCCESS = 'PRODUCTS_GET_NEW_LIST_SUCCESS'
export const PRODUCTS_GET_NEW_LIST_FAIL = 'PRODUCTS_GET_NEW_LIST_FAIL'

export const PRODUCTS_GET_LIST_START = 'PRODUCTS_GET_LIST_START'
export const PRODUCTS_GET_LIST_SUCCESS = 'PRODUCTS_GET_LIST_SUCCESS'
export const PRODUCTS_GET_LIST_FAIL = 'PRODUCTS_GET_LIST_FAIL'

export const PRODUCTS_GET_DETAIL_START = 'PRODUCTS_GET_DETAIL_START'
export const PRODUCTS_GET_DETAIL_SUCCESS = 'PRODUCTS_GET_DETAIL_SUCCESS'
export const PRODUCTS_GET_DETAIL_FAIL = 'PRODUCTS_GET_DETAIL_FAIL'

export const PRODUCTS_APPROVE_START = 'PRODUCTS_APPROVE_START'
export const PRODUCTS_APPROVE_SUCCESS = 'PRODUCTS_APPROVE_SUCCESS'
export const PRODUCTS_APPROVE_FAIL = 'PRODUCTS_APPROVE_FAIL'

export const PRODUCTS_DECLINE_START = 'PRODUCTS_DECLINE_START'
export const PRODUCTS_DECLINE_SUCCESS = 'PRODUCTS_DECLINE_SUCCESS'
export const PRODUCTS_DECLINE_FAIL = 'PRODUCTS_DECLINE_FAIL'

export const CATEGORIES_GET_LIST_START = 'CATEGORIES_GET_LIST_START'
export const CATEGORIES_GET_LIST_SUCCESS = 'CATEGORIES_GET_LIST_SUCCESS'
export const CATEGORIES_GET_LIST_FAIL = 'CATEGORIES_GET_LIST_FAIL'

export const CATEGORIES_CREATE_START = 'CATEGORIES_CREATE_START'
export const CATEGORIES_CREATE_SUCCESS = 'CATEGORIES_CREATE_SUCCESS'
export const CATEGORIES_CREATE_FAIL = 'CATEGORIES_CREATE_FAIL'

export const CATEGORIES_CREATE_SUB_START = 'CATEGORIES_CREATE_SUB_START'
export const CATEGORIES_CREATE_SUB_SUCCESS = 'CATEGORIES_CREATE_SUB_SUCCESS'
export const CATEGORIES_CREATE_SUB_FAIL = 'CATEGORIES_CREATE_SUB_FAIL'

export const CATEGORIES_RENAME_START = 'CATEGORIES_RENAME_START'
export const CATEGORIES_RENAME_SUCCESS = 'CATEGORIES_RENAME_SUCCESS'
export const CATEGORIES_RENAME_FAIL = 'CATEGORIES_RENAME_FAIL'

export const CATEGORIES_RENAME_SUB_START = 'CATEGORIES_RENAME_SUB_START'
export const CATEGORIES_RENAME_SUB_SUCCESS = 'CATEGORIES_RENAME_SUB_SUCCESS'
export const CATEGORIES_RENAME_SUB_FAIL = 'CATEGORIES_RENAME_SUB_FAIL'

export const VENDOR_GET_PENDING_LIST_START = 'VENDOR_GET_PENDING_LIST_START'
export const VENDOR_GET_PENDING_LIST_SUCCESS = 'VENDOR_GET_PENDING_LIST_SUCCESS'
export const VENDOR_GET_PENDING_LIST_FAIL = 'VENDOR_GET_PENDING_LIST_FAIL'

export const VENDOR_GET_LIST_START = 'VENDOR_GET_LIST_START'
export const VENDOR_GET_LIST_SUCCESS = 'VENDOR_GET_LIST_SUCCESS'
export const VENDOR_GET_LIST_FAIL = 'VENDOR_GET_LIST_FAIL'

export const VENDOR_APPROVE_START = 'VENDOR_APPROVE_START'
export const VENDOR_APPROVE_SUCCESS = 'VENDOR_APPROVE_SUCCESS'
export const VENDOR_APPROVE_FAIL = 'VENDOR_APPROVE_FAIL'

export const VENDOR_DECLINE_START = 'VENDOR_DECLINE_START'
export const VENDOR_DECLINE_SUCCESS = 'VENDOR_DECLINE_SUCCESS'
export const VENDOR_DECLINE_FAIL = 'VENDOR_DECLINE_FAIL'

export const BUYER_GET_LIST_START = 'BUYER_GET_LIST_START'
export const BUYER_GET_LIST_SUCCESS = 'BUYER_GET_LIST_SUCCESS'
export const BUYER_GET_LIST_FAIL = 'BUYER_GET_LIST_FAIL'