export const TOKEN_GET_START = 'TOKEN_GET_START'
export const TOKEN_GET_SUCCESS = 'TOKEN_GET_SUCCESS'
export const TOKEN_GET_FAIL = 'TOKEN_GET_FAIL'

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const PRODUCTS_GET_NEW_LIST_START = 'PRODUCTS_GET_NEW_LIST_START'
export const PRODUCTS_GET_NEW_LIST_SUCCESS = 'PRODUCTS_GET_NEW_LIST_SUCCESS'
export const PRODUCTS_GET_NEW_LIST_FAIL = 'PRODUCTS_GET_NEW_LIST_FAIL'